---
title: "Notes: Mas-Colell Chapter 10 Competitive Markets"
author: "Yuki KAYABA"
date: "1/2/2023"
site: bookdown::bookdown_site
output:
  bookdown::gitbook: default
#output_dir: docs
#bookdown::gitbook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bookdown)
```

# 10.A Introduction

## Goal of this chapeter
- To formally introduce and study two key concepts, the notions of _Pareto optimality_ and _competitive equilibrium_.
- To develop a somewhat special but analytically very tractable context for the study of market equilibrium, the _partial equilibrium model_.

# 10.B Pareto Optimality and Competitive Equilibria

セッテイングと定義・定理のみ簡単にまとめておく。

- $i = 1, ..., I$ consumers
- $j = 1, ..., J$ firms
- $l = 1, ..., L$ goods
- $x_{i} = (x_{1, i}, ... x_{L, i}) \in X_{i}$: consumer $i$'s consumption bundles
- $u_{i}(\cdot)$: consumer $i$'s utility function that represents consumer $i$'s preferences over consumption bundles
- $\omega_{l} \geq 0$ for $l = 1, ..., L$: endowment of good $l$
- $Y_{j} \subset \mathbb{R}^{L}$: firm $j$'s production set
- $y_{j} = (y_{1j}, ..., y_{Lj}) \in Y_{j}$: firm $j$'s production vector
- The total net amount of goo $l$ available to the economy is $\omega_{l} + \sum_{j}y_{lj}$

**Definition 10.B.1**
An _economic allocation_ $(x_{1}, ..., x_{I}, y_{1}, ..., y_{J})$ is a specification of a consumption of vector $x_{i} \in X_{i}$ for each consumer $i = 1, ..., I$ and a production vector $y_{j} \in Y_{j}$ for each firm $j = 1, ..., J$. The allocation $(x_{1}, ..., x_{I}, y_{1}, ..., y_{J})$ is _feasible_ if

$$
\sum_{i = 1}^{I}x_{li} \leq \omega_{l} + \sum_{j}y_{lj}
$$

## Pareto Optimality

**Definition 10.B.2**
A feasible allocation $(x_{1}, ..., x_{I}, y_{1}, ..., y_{J})$ is _Pareto optimal_ if there is no other feasible allocation $(x'_{1}, ..., x'_{I}, y'_{1}, ..., y'_{J})$ such that $u_{i}(x'_{i}) \geq u_{i}(x_{i})$ for all $i = 1, ..., I$ and $u_{i}(x'_{i}) > u_{i}(x_{i})$ for some $i$

## Competitive Equilibria

- Suppose that consumer $i$ initially owns $\omega_{li}$ of good $l$, where $\sum_{i}\omega_{li} = \omega_{l}$
- $\omega_{i} = (\omega_{1i}, ..., \omega_{Li})$: consumer $i$'s vector of endowments
- Suppose that consumer $i$ owns a share $\theta_{if}$ of firm $j$ (where $\sum_{i}\theta_{ij} = 1$), giving him a claim to fraction $\theta_{ij}$ of firm $j$'s profits

**Definition 10.B.3**
The allocation $(x^{*}_{1}, ..., x^{*}_{I}, y^{*}_{1}, ..., y^{*}_{J})$ and price vector $p^{*} \in \mathbb{R}^{L}$ constitute a _competitive equilibrium_ if the following conditions are satisfied:

1. _Profit maximization_: For each firm $j$, $y^{*}_{j}$ solves

$$
\max_{y_{j} \in Y_{j}} p^{*} \cdot y_{j}
$$

2. _Utility maximization_: For each consumer $i$, $x^{*}_{i}$ solves

$$
\begin{align}
  \max_{x_{i} \in X_{i}} u_{i}(x_{i}) \\
  \text{s.t.} \quad p^{*} \cdot x_{i} \leq p^{*} \cdot \omega_{i} + \sum_{j = 1}^{J}\theta_{ij}(p^{*} \cdot y^{*}_{j})
\end{align}
$$

3. _Market clearing_: For each good $l = 1, ..., L$,

$$
\sum_{i = 1}^{I}x^{*}_{li} = \omega_{l} + \sum_{j}y^{*}_{lj}
$$

**Lemma 10.B.1**
If the allocation $(x_{1}, ..., x_{I}, y_{1}, ..., y_{J})$ and price vector $p >> 0$ satisfy the market clearing condition for all goods $l \neq k$, and if every consumer's budget constraint is satisfied with equality, so that $p \cdot x_{i} = p \cdot \omega_{i} + \sum_{j = 1}^{J}\theta_{ij}(p \cdot y_{j})$ for all $i$, then the marked for good $k$ also clears


# 10.C Parial Equilibrium Competitive Analysis

実証IOは基本的に特定のマーケットにフォーカスした部分均衡分析であるため考え方を整理しておく。

Partial equilibrium analysis is justified by the following reasons:

- When the expenditure on the good under study is a small portion of a
consumer's total expenditure, only a small fraction of any additional doller of wealth will be spent on this good; consequently, we can expect wealth effects for it to be small.
- With similarly dispersed substitution effects, the small size of the market under study should lead the prices of other goods to be appoximately unaffected by changes in this market.

→要は他の市場における財との所得効果・代替効果が小さく、他の市場の需要・価格に影響をおよぼさない場合部分均衡分析が正当化される。

## Demand Side

- Each consumer $i = 1, ..., I$ has a utility function: 
$$
u(x_{i}, m_{i}) = m_{i} + \phi_{i}(x_{i})
$$
where $x_{i}$ is consumer $i$'s consumption of good $l$, the good whose market is under study, and $m_{i}$ is the consumption of the numeraire.

→上記justificationの通り、所得効果のないモデルを考えたいので準線形の効用関数を考える。

- $\phi'_{i}(x_{i}) > 0$ and $\phi''_{i}(x_{i}) < 0$ at all $x_{i} \geq 0$.
- Normalize $\phi_{i}(x_{i}) = 0$.
- Let $p$ denote the price of good $l$ and the price of the numeraire is normalized to 1.
- Consumer $i$'s initial endowment of the numeraire is the scalar $\omega_{mi} > 0$ and let $\omega_{m} = \sum_{i}\omega_{mi}$.

## Supply Side

- Each firm $j = 1, ..., J$ in this two-good economy is able to produce good $l$ from good $m$.
- Cost function: $c_{l}(q_{j})$, the amount of the numeraire required by firm $j$ to produce $q_{j}$ units of good $l$.
- $c_{j}(\cdot)$ is twice differentiable, with $c'_{j}(q_{j}) > 0$ and $c''_{j}(q_{j}) > 0$ at all $q_{j} \geq 0$.
- Let $z_{j}$ denote firm $j$'s use of good $m$ as an input.
- Production set: $Y_{j} = \{(-z_{j}, q_{j}): q_{j} \geq 0 \quad \text{and} \quad z_{j} \geq c_{j}(q_{j})\}$.
- There is no initial endowment of good $l$, so that all amounts consumerd must be produced by the firms.

## Competitive Equilibria

競争均衡については10.B.3参照。ざっくりいえば①各企業の利潤最大化、②各消費者の効用最大化、③
マーケットクリアリングを満たす配分および価格を指す。

- Profit maximization: given the price $p^{*}$ for good $l$, firm $j$'s equilibrium output level $q^{*}_{j}$ must solve
$$
\max_{q_{j} \geq 0} p^{*}q_{j} - c_{j}(q_{j}),
$$
which has the necessary and sufficient FOC
$$
p^{*} \leq c'_{j}(q^{*}_{j}), \quad \text{with equality if} \quad q^{*}_{j} > 0.
$$

- Utility maximization: consumer $i$'s equilibrium consumption vector $(m^{*}_{i}, x^{*}_{i})$ must solve
$$
\max_{m_{i} \in \mathbb{R}, x_{i} \in \mathbb{R}_{+}} m_{i} + \phi_{i}(x_{i}) \\
\text{s.t.} \quad m_{i} + p^{*}x_{i} \leq \omega_{mi} + \sum^{J}_{j = 1}\theta_{ij}(p^{*}q^{*}_{j} - c_{j}(q^{*}_{j})).
$$
which has the necessary and sufficient FOC
$$
\phi'_{i}(x^{*}_{i}) \leq p^{*}, \quad \text{with equality if} \quad x^{*}_{i} > 0.
$$

- Market Clearing: If the market for good $l$ clears, then the market for the numeraire also clears (Lemma 10.B.1). Thus we need only check that the market for good $l$ clears.

- Hence, the allocation $(x^{*}_{1}, ... x^{*}_{I}, q^{*}_{1}, ..., q^{*}_{J})$ and the price $p^{*}$ constitute a competitive equilibrium if and only if:
$$
p^{*} \leq c'_{j}(q^{*}_{j}), \quad \text{with equality if} \quad q^{*}_{j} > 0 \\
\phi'_{i}(x^{*}_{i}) \leq p^{*}, \quad \text{with equality if} \quad x^{*}_{i} > 0 \\
\sum^{I}_{i = 1}x^{*}_{i} = \sum^{J}_{j = 1}q^{*}_{j} 
$$

- The above equilibrium conditions have a property: the equilibrium allocation and price are independent of the distribution of endowments and ownership shares.
- This property comes from the quasilinear form of consumer preferences.

## Comparative Statics

- 比較静学は実証IOでもよく使う概念（外性パラメータの変化が経済厚生に与えるインパクトを反実仮想）
- It is often of interest to determine how a change in underlying market conditions affects the equilibrium outcome of a competitive market.
- Generally, compare outcomes that results from changes in exogenous parameters.
  - consumer's preferences are affected by a vector of exogenous parameters $\alpha \in \mathbb{R}^{M}$, so that the utility function $\phi_{i}(\cdot)$ can be written as $\phi_{i}(x_{i}, \alpha)$.
  - each firm's technology may be affected by a vector of exogenous parameters $\beta \in \mathbb{R}^{S}$, so that the cost function $c_{j}(\cdot)$ can be written as $c_{j}(q_{j}, \beta)$.
  - consumers and firms may face taxes or subsidies that may make the effective price paid or received differ from the market price $p$, so that the effective price paid by consumer $i$ and the effective price received by firm $j$ given tax and subsidy parameters $t \in \mathbb{R}^{K}$ can be written as $\hat{p}_{i}(p, t)$ and $\hat{p}_{j}(p, t)$, respectively.
- For given values $(\alpha, \beta, t)$ of the parameters, the $I + J$ equilibrium quantities $(x^{*}_{1}, ... x^{*}_{I}, q^{*}_{1}, ..., q^{*}_{J})$ and the equilibrium price $p^{*}$ are determined by the following $I + J + 1$ equiations:

$$
\phi'_{i}(x^{*}_{i}, \alpha) = p^{*} \quad i = 1, ..., I.  \\
c'_{j}(q^{*}_{j}, \beta) = \hat{p}_{j}(p^{*}, t) \quad j = 1, ..., J \\
\sum^{I}_{i = 1}x^{*}_{i} = \sum^{J}_{j = 1}q^{*}_{j} 
$$

# 10.D The Fundamental Welfare Theorems in a Partial Equilibrium Context

- 一般均衡と同じように、部分均衡においても厚生経済学の第一定理、第二定理が成立する。
- ただし、効用が準線形であることが必要。

## The First Fundamental Theorem of Welfare Economics

**Proposition 10.D.1 (The First Fundamental Theorem of Welfare Economics)**

If the price $p^{*}$ and allocation $(x^{*}_{1}, ... x^{*}_{I}, q^{*}_{1}, ..., q^{*}_{J})$ constitute a competitive equilibrium, then this allocation is Pareto optimal.

- When consumer preferences are quasilinear, the boundary of the economy's utility possibility set is linear and all points in this boundary are associated with consumption allocations that differ only in distribution of the numerarire among consumers.

## The Second Fundamental Theorem of Welfare Economics

**Proposition 10.D.2 (The Second Fundamental Theorem of Welfare Economics)**

For any Pareto optimal levels of utility $(u^{*}_{1}, ..., u^{*}_{I})$, there are transfers of the numeraire commodity $(T_{1}, ..., T_{I})$ satisfying $\sum_{i}T_{i} = 0$, such that a competitive equilibrium reached from the endowments $(\omega_{m1} + T_{1}, ..., \omega_{mI} + T_{I})$ yields precisely the utilities $u^{*}_{1}, ..., u^{*}_{I}$.













